using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Microsoft.PowerApps.Tools.AppEntities
{
    [Serializable]
    public class EntityData
    {
        public List<Entity> Entities { get; set; }
        public List<UserTemplate> UsedTemplates { get; set; }
    }

    public class OverridableProperties
    {
    }

    public class UserTemplate
    {
        public string Version { get; set; }
        public string Name { get; set; }
        public string Template { get; set; }
    }

    public class Template
    {
        public string Id { get; set; }
        public string Version { get; set; }
        public string Name { get; set; }
        public bool IsCustomGroupControlTemplate { get; set; }
        public string CustomGroupControlTemplateName { get; set; }
        public OverridableProperties OverridableProperties { get; set; }
    }

    public class Wadlmetadata
    {
        public string WadlXml { get; set; }
        public string SwaggerJson { get; set; }
    }

    public class Entity
    {
        public string Type { get; set; }
        public string Name { get; set; }
        public string ServiceKind { get; set; }
        public Wadlmetadata WadlMetadata { get; set; }
        public string ApiId { get; set; }
        //public string Schema { get; set; }
        public bool IsSampleData { get; set; }
        public bool IsWritable { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string Content { get; set; }
        public string ResourceKind { get; set; }
        public string RootPath { get; set; }
        public string OriginalSchema { get; set; }
        public string Data { get; set; }
        public string OriginalName { get; set; }
        public string[] OrderedColumnNames { get; set; }
        public string DatasetName { get; set; }
        public string TableName { get; set; }
        public Cdprevision CdpRevision { get; set; }
        public Dataentitymetadatajson DataEntityMetadataJson { get; set; }
        public Connecteddatasourceinfonamemapping ConnectedDataSourceInfoNameMapping { get; set; }
        public Template Template { get; set; }
        public float Index { get; set; }
        public float PublishOrderIndex { get; set; }
        public string VariantName { get; set; }
        public string LayoutName { get; set; }
        public string MetaDataIDKey { get; set; }
        public bool PersistMetaDataIDKey { get; set; }
        public bool IsFromScreenLayout { get; set; }
        public string StyleName { get; set; }
        public string Parent { get; set; }
        public bool IsDataControl { get; set; }
        public bool IsGroupControl { get; set; }
        public bool IsAutoGenerated { get; set; }
        public List<Rule> Rules { get; set; }
        public Controlpropertystate[] ControlPropertyState { get; set; }
        public bool IsLocked { get; set; }
        public string ControlUniqueId { get; set; }
        public List<Entity> Children { get; set; }
        public Controlthisitemtype ControlThisItemType { get; set; }
        public string[] GroupedControlsKey { get; set; }

    }

    public class Controlthisitemtype
    {
        public string Version { get; set; }
        public Type Type { get; set; }
    }

    public class Type
    {
        public string Name { get; set; }
        public string Kind { get; set; }
        public string EnumString { get; set; }
        [JsonProperty(PropertyName = "Type")]
        public Type1[] Type1 { get; set; }
        public string[] ProjectionInfoDataSources { get; set; }
    }

    public class Type1
    {
        public string Name { get; set; }
        public string Kind { get; set; }
        public string EnumString { get; set; }
        public Dataentity DataEntity { get; set; }
        public object[] Type { get; set; }
        public Optionset OptionSet { get; set; }
        public Attachment Attachment { get; set; }
    }

    public class Dataentity
    {
        public string EntityInfoIdentity { get; set; }
        public string EntityInfoName { get; set; }
        public bool EntityInfoIsTable { get; set; }
        public string EntityInfoParentDSName { get; set; }
        public string EntityInfoRelatedEntityPath { get; set; }
    }

    public class Optionset
    {
        public bool OptionSetIsValue { get; set; }
        public string OptionSetName { get; set; }
    }

    public class Attachment
    {
        public string Version { get; set; }
        public Type1 Type { get; set; }
    }

    public class Connecteddatasourceinfonamemapping
    {
    }

    public class Dataentitymetadatajson
    {
        public string _0f2c1402395448c3966c29af3ce8abf8 { get; set; }
        public string cd4c06dfc1854e528710f3cee2ae6f2e { get; set; }
        public string _77fc8f452de84e8fa695e8dc90844bb5 { get; set; }
    }

    public class Cdprevision
    {
        public float RevisionNumber { get; set; }
        public string BaseUrl { get; set; }
        public DateTime LastChangedTimeString { get; set; }
    }

    public class Rule
    {
        public string Property { get; set; }
        public string Category { get; set; }
        public string InvariantScript { get; set; }
        public string NameMap { get; set; }
    }

    public class Controlpropertystate
    {
        public string InvariantPropertyName { get; set; }
        public bool AutoRuleBindingEnabled { get; set; }
        public string AutoRuleBindingString { get; set; }
        public string NameMapSourceSchema { get; set; }
        public bool IsLockable { get; set; }
        public string AFDDataSourceName { get; set; }
        public string NameMap { get; set; }
    }
}